create view ng_intermediate_data_store.load_servicerequest_activity as
	select
	    ssa.activity_sysid as id,
	    ssa.activity_type as type,
        ssa.activity_subtype as sub_type,
        ssa.name as summary,
        ssa.status as status,
        ssa.priority as priority,
        ssa.comm_channel as channel,
        ssa.add_date as created_on,
        ssa.add_username as created_by,
        ssa.update_date as updated_on,
        ssa.update_username as updated_by,
        json_build_object(
                'protected_card_sysid', ssa.protected_card_sysid,
                'bank_account_sysid', ssa.bank_account_sysid,
                'generic_asset_sysid', ssa.generic_asset_sysid,
                'bank_branch_sysid', ssa.bank_branch_sysid,
                'planned_start_date', ssa.planned_start_date,
                'actual_start_date', ssa.actual_start_date,
                'req_completion_date', ssa.req_completion_date,
                'actual_completion_date', ssa.actual_completion_date,
                'comments', ssa.comments,
                'contact_method', ssa.contact_method,
                'duplicate_touchpoint_flag', ssa.duplicate_touchpoint_flag,
                'email_address', ssa.email_address,
                'fax_numeric', ssa.fax_numeric,
                'new_protected_card_sysid', ssa.new_protected_card_sysid,
                'new_bank_account_sysid', ssa.new_bank_account_sysid,
                'new_generic_asset_sysid', ssa.new_generic_asset_sysid,
                'phone_numeric', ssa.phone_numeric,
                'sla_target1', ssa.sla_target1,
                'sla_target2', ssa.sla_target2,
                'status_date', ssa.status_date,
                'touchpoint_flag', ssa.touchpoint_flag,
                'ext_activity_id', ssa.ext_activity_id,
                'activity_lstcrd_sysid', ssa.activity_lstcrd_sysid,
                'issuer_contact_sysid', ssa.issuer_contact_sysid,
                'lost_stolen_card_sysid', ssa.lost_stolen_card_sysid,
                'loss_center_comments', ssa.loss_center_comments,
                'activity_pmt_sysid', ssa.activity_pmt_sysid,
                'payment_sysid', ssa.payment_sysid,
                'payment_vehicle_sysid', ssa.payment_vehicle_sysid,
                'flow_type', ssa.flow_type,
                'amount', ssa.amount,
                'currency', ssa.currency,
                'payment_status_sysid', ssa.payment_status_sysid,
                'activity_payment_add_date', ssa.activity_payment_add_date,
                'activity_payment_add_username', ssa.activity_payment_add_username,
                'activity_payment_update_date', ssa.activity_payment_update_date,
                'activity_payment_update_username', ssa.activity_payment_update_username,
                'eft_description', ssa.eft_description,
                'payment_comments', ssa.payment_comments,
                'activity_corr_sysid', ssa.activity_corr_sysid,
                'legacy_template', ssa.legacy_template,
                'comm_transaction_id', ssa.comm_transaction_id,
                'corr_free_text', ssa.corr_free_text,
                'activity_corr_add_date', ssa.activity_corr_add_date,
                'activity_corr_add_username', ssa.activity_corr_add_username,
                'activity_corr_update_date', ssa.activity_corr_update_date,
                'activity_corr_update_username', ssa.activity_corr_update_username,
                'comm_type_id', ssa.comm_type_id,
                'kit_id', ssa.kit_id
            )
        as additionalData
    from ng_intermediate_data_store.stage_service_activity ssa
    left join
    where ssa.activity_sysid > 522286686
;