class Mappings:
    level_zero_mapping = {"benefitsExplained": "benefits_explained",
                          "compensationAmount": "comp_amount",
                          "compensationAmountCurrency": "comp_amount_currency",
                          "dateOfLoss": "loss_date",
                          "receivedDateFromPartner": "received_date_from_partner",
                          "detailNotExplained": "detl_not_explained",
                          "exclusionsHighlighted": "excl_highlighted",
                          "featuresExplained": "feat_explained",
                          "placeOfLoss": "place_of_loss",
                          "product": "product",
                          "complainant": "complainant",
                          "complaintReason": "reason",
                          "replyTo": "reply_to",
                          "receivedBy": "received_by",
                          "notes": "preference_notes",
                          "deliveryName": "rqst_cb_evt_book_delivery_name",
                          "eventBkngCancelReason": "evnt_bkng_cancel_reason",
                          "deliveryEmail": "rqst_cb_evt_book_add_username",
                          "eventCategoryName": "evnt_catgry_name",
                          "eventDate": "entrtnmnt_evnt_date",
                          "eventName": "entrtnmnt_evnt_name",
                          "eventOnsaleDate": "evnt_onsale_date",
                          "maxTicketPrice": "max_ticket_price",
                          "minTicketPrice": "min_ticket_price",
                          "possiblePerformances": "possible_performances",
                          "preferenceNotes": "preference_notes",
                          "prefTicketPrice": "pref_ticket_price",
                          "preRegistrationFlag": "rqst_cb_evt_book_preregistration_fl",
                          "specialRequirements": "special_reqs",
                          "ticketCurrency": "ticket_currency",
                          "ticketDeliveryType": "reg_evt_bkng_ticket_delivery_type",
                          "ticketProviderName": "reg_evt_bkng_ticket_provider",
                          "totalTicketsQty": "reg_evt_bkng_total_tickets_qty",
                          "vendorEventRef": "rqst_cb_evt_book_vendor_event_ref",
                          "cost": "transaction_amount",
                          "eventDate": "entrtnmnt_evnt_date",
                          "fulfillmentDate": "activation_date",
                          "supplier": "voucher_supplier"
                          }
    deliveryAddress_mappings = {
        "address1": "address_1",
        "address2": "address_2",
        "address3": "address_3",
        "city": "city",
        "county": "county",
        "postalCode": "postal_code",
        "countryISOCode": "county",
        "countryName": "country",
        "phoneNumber": "phone_num",
        "phoneNumber2": "phone_num_2",
        "mobileNumber": "mobile_num"
    }
    onsaleRegEventBookingPreference_mappings = {
        "preference1": "preference_1",
        "preference2": "preference_2",
        "preference3": "preference_3",
        "preference4": "preference_4",
        "preference5": "preference_5",
        "dateCreated": "received_date",
        "userCreated": "received_by",
        "userModified": "update_username",
        "dateModified": "update_date"
    }
    bookCashbackEvent_mappings = {
        "deliveryName": "rqst_cb_evt_book_delivery_name",
        "deliveryEmailAddress": "rqst_cb_evt_book_add_username",
        "bookingDate": "rqst_cb_evt_book_add_date",
        "bookingReference": "bkng_refrnc_nr",
        "cancellationReason": "evnt_bkng_cancel_reason",
        "cashBackInEligibleFlag": "cb_ineligible_fl",
        "cashBackLastBookingFlag": "cb_last_booking_fl",
        "extraCashBackAmountPercentage": "extra_cashback_pct_id",
        "extraCashBackAmountValue": "extra_cb_amt",
        "eventCategoryName": "evnt_catgry_name",
        "eventDate": "entrtnmnt_evnt_date",
        "eventName": "entrtnmnt_evnt_name",
        "onSaleRegRequestId": "onsale_reg_evt_bkng_id",
        "currency": "ticket_currency",
        "orderRef": "rqst_cb_evt_book_source_order_ref",
        "postage": "postal_code",
        "preRegistrationFlag": "rqst_cb_evt_book_preregistration_fl",
        "purchaseDate": "purchase_date",
        "ticketdeliveryType": "reg_evt_bkng_ticket_delivery_type",
        "ticketProviderName": "reg_evt_bkng_ticket_provider",
        "totalActualPrice": "total_price_amt",
        "totalBookingFee": "total_bkng_fee_amt",
        "totalNumOfTickets": "transaction_ticket_quantity",
        "totalPriceAfterCashBack": "total_price_after_cb_amt",
        "vendorEventRef": "rqst_cb_evt_book_vendor_event_ref",
        "venueCityName": "venue_city",
        "venueName": "venue_id",
        "venueNameOther": "venue_other_name",
        "cashBackId": "cb_evnt_bkng_sysid",
        "seatReferences": "seat_details_txt"
    }

    bookCashbackEvent_payment_mappings = {}  # All nulls not required
    bookCashbackEvent_deliveryAddress_mappings = {
        "address1": "address_1",
        "address2": "address_2",
        "address3": "address_3",
        "city": "city",
        "county": "county",
        "postalCode": "postal_code",
        "countryName": "country",
        "phoneNumber": "phone_num",
        "phoneNumber2": "phone_num_2",
        "mobileNumber": "mobile_num"
    }
    cinemaStoreVoucher_mappings = {
        "customerFirstName": "customer_firstname",
        "customerLastName": "customer_lastname",
        "customerEmail": "voucher_header_customer_email",
        "voucherSupplier": "voucher_supplier",
        "transactionTotalAmount": "transaction_amount",
        "transactionAmountExcludingVat": "trans_amount_excluding_vat",
        "transactionVoucherQuantity": "transaction_voucher_quantity",
        "transactionTicketQuantity": "transaction_ticket_quantity",
        "transactionDate": "transaction_date",
        "transactionPdfUrl": "voucher_header_transaction_pdf_url",
        "sourceOrderReference": "voucher_header_source_order_ref",
        "dateCreated": "received_date",
        "userCreated": "received_by",
        "userModified": "update_username",
        "dateModified": "update_date"
    }