class MappingsBE:
    level_zero_mapping ={
        "bookingReference":"bkng_refrnc_nr",
        "currency":"GBP",
        "unitCurrency": "GBP",
        "service":"Events: Booking Services",
        "customerFirstName":"customer_firstname",
        "customerLastName":"customer_lastname",
        "customerPhoneNumber":"mobile_num",
        "totalBookingFee":"total_bkng_fee_amt",
        "postageFee":"postage_amt",
        "totalActualPrice":"total_price_amt",
        "totalPriceAfterCashback":"total_price_after_cb_amt",
        "extraCashbackPercentage":"extra_cashback_pct_desc",
        "extraCashback":"extra_cb_amt",
        "deliveryName":"rqst_cb_evt_book_delivery_name",
        "deliveryType": "rqst_cb_evt_book_ticket_delivery_type_desc",
        "ticketProvider": "reg_evt_bkng_ticket_provider",
        "bookingDate": "booking_date",
        "cancellationReason":  "evnt_bkng_cancel_reason",
        "isEligibleForCashback":"cb_ineligible_fl",
        "channel":  "channel",
        "subStatus":  "substatus",
        "comments":  "internal_comments",
        "isLastCashbackBooking":"cb_last_booking_fl",
        "onSaleRegRequestId": "onsale_reg_evt_bkng_id",
        "status": "status",
        "transactionDate": "transaction_date",
        "transactionPdfUrl": "voucher_header_transaction_pdf_url",
        "transactionVoucherQuantity": "transaction_voucher_quantity",
        "transactionTicketQty": "transaction_ticket_quantity",
        "transactionTotalAmount": "transaction_amount",
        "voucherSupplier": "voucher_supplier",
        "deliveryEmail": "rqst_cb_evt_book_add_username",
        "alternateEmail": "null",
        "maxPrice": "max_ticket_price",
        "minPrice": "min_ticket_price",
        "onSaleDate": "evnt_onsale_date",
        "preferredPrice": "pref_ticket_price",
        "preferredSeating": "preference_notes",
        "specialRequirements": "special_reqs",
        "preRegistrationFlag": "rqst_cb_evt_book_preregistration_fl",
        "possiblePerformances": "possible_performances",
        "commentsIntern": "internal_comments",
        "receivedDate": "received_date_from_partner",
        "statusReason":"reason",
        "thirdPartyPhone": "null",
        "thirdParty": "null",
        "transactionAmount": "transaction_amount",
        "compensationAmount": "comp_amount",
        "compensationType": "compensation_type",
        "complainant": "complainant",
        "complaintDetail": "null",
        "complaintNature": "null",
        "complaintReason": "reason",
        "complaintResolution": "resolution_desc",
        "dateReceived": "received_date",
        "eventDateTime": "complaint_add_date",
        "receivedBy": "received_by",
        "replyTo": "reply_to",
        "severity": "severity",
        "thirdPartyNotes": "null",
        "resolutionSummary": "resolution_desc",
        'extraDiscountPercentage': "0",
        'totalPriceAfterDiscount': "total_price_after_discnt_amt"
    }
    deliveryAddress_mappings = {
        "addressLine1": "address_1",
        "addressLine2": "address_2",
        "addressLine3": "address_3",
        "city": "city",
        "county": "county",
        "postalCode": "postal_code",
        "phoneNumber": "phone_num",
        "alternatePhoneNumber": "phone_num_2",
        "mobileNumber": "mobile_num"
    }

    level_zero_details_mappings ={
        "eventName": "entrtnmnt_evnt_name",
        "category": "evnt_catgry_name",
        "dateTime": "entrtnmnt_evnt_date",
        "otherVenueName": "venue_other_name",
        "venue": "venue_desc",
        "city": "venue_city"
    }
    seats_deatils_mappings={
        "additionalDetails":"seat_details_txt"
    }

    field_date_format_mappings=["transactionDate","bookingDate","onSaleDate","dateReceived","eventDateTime"]