-- with sr as (
-- INSERT INTO migration.servicerequest(
-- id,
-- additional_data,
-- created_by,
-- created_on,
-- updated_by,
-- updated_on,
-- description,
-- member,
-- owner,
-- status,
-- sub_status,
-- sub_type,
-- summary,
-- type)
-- );